name = "hotwire-todo"
main = "build/worker.entrypoint.mjs"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat"]


# Replace database_id after `wrangler d1 create hotwire-todo`.
[[d1_databases]]
binding = "DB"
database_name = "hotwire-todo"
database_id = "2052ba28-fd8f-4642-81f6-176fb0e0a6c2"
migrations_dir = "db/migrate"
