# frozen_string_literal: true
source 'https://rubygems.org'

ruby '>= 3.4.0'

# All gems below are pulled from RubyGems. Per the project rule in
# CLAUDE.md, this Gemfile must NOT link any unreleased local gem;
# new versions get `gem build` + `gem push`-ed first.
gem 'opal-homura', '= 1.8.3.rc1.5', require: 'opal'
gem 'homura-runtime', '= 0.3.6'
gem 'sinatra-homura', '= 0.3.2'
gem 'sinatra-inertia', '= 0.1.4'
gem 'sequel-d1', '= 0.3.1'

gem 'rake'
gem 'sequel', '~> 5.0'
gem 'sqlite3', '>= 2.0'
