name = "inertia-todo"
main = "build/worker.entrypoint.mjs"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat"]


# Replace database_id after `wrangler d1 create inertia-todo`.
[[d1_databases]]
binding = "DB"
database_name = "inertia-todo"
database_id = "0d469d3c-665d-4764-ab28-4e75cbb0ad95"
migrations_dir = "db/migrate"
