# frozen_string_literal: true
source 'https://rubygems.org'

ruby '>= 3.4.0'

# Monorepo dev (this example lives under homura `examples/`).
gem 'opal-homura', path: '../../vendor/opal-gem', require: 'opal'
gem 'homura-runtime', path: '../../gems/homura-runtime'
gem 'sinatra-homura', path: '../../gems/sinatra-homura'
