# frozen_string_literal: true
source 'https://rubygems.org'

ruby '>= 3.4.0'

# Monorepo dev (this example lives under homurabi `examples/`).
gem 'opal', path: '../../vendor/opal-gem'
gem 'cloudflare-workers-runtime', path: '../../gems/cloudflare-workers-runtime'
gem 'sinatra-cloudflare-workers', path: '../../gems/sinatra-cloudflare-workers'
