name = "blog"
main = "build/worker.entrypoint.mjs"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat"]


# Replace database_id after `wrangler d1 create blog`.
[[d1_databases]]
binding = "DB"
database_name = "blog"
database_id = "097a304e-781b-45db-98b3-ac8f8e15dbc9"
migrations_dir = "db/migrate"
