# frozen_string_literal: true
source 'https://rubygems.org'

ruby '>= 3.4.0'

gem 'rake'
gem 'opal-homura', '= 1.8.3.rc1.5', require: 'opal'
gem 'homura-runtime', '= 0.3.1'
gem 'sinatra-homura', '= 0.3.0'
gem 'sequel-d1', '= 0.3.1'
gem 'sequel', '~> 5.0'
gem 'sqlite3', '>= 2.0'

group :development, :test do
  gem 'playwright-ruby-client', '~> 1.50'
end
