name = "todo-orm"
main = "build/worker.entrypoint.mjs"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat"]


# Replace database_id after `wrangler d1 create todo-orm`.
[[d1_databases]]
binding = "DB"
database_name = "todo-orm"
database_id = "b1e3a6f0-2f68-4823-986f-d66436ac1315"
migrations_dir = "db/migrate"

