name = "todo"
main = "build/worker.entrypoint.mjs"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat"]


# Replace database_id after `wrangler d1 create todo`.
[[d1_databases]]
binding = "DB"
database_name = "todo"
database_id = "753df7cf-873b-4a7d-ae05-ab27a42f48b0"
migrations_dir = "db/migrate"
