#!/usr/bin/env ruby
# frozen_string_literal: true
# Generates app/routes/fragments/route_XXX.rb + bootstrap.rb + domain loaders from app/routes/all.rb

require 'fileutils'

ROOT = File.expand_path('..', __dir__)
# Monolithic route table kept for regeneration (see app/routes/canonical_all.rb).
ALL  = File.join(ROOT, 'app/routes/canonical_all.rb')
FRAG = File.join(ROOT, 'app/routes/fragments')

ROUTE_HEAD = /^  (get|post|put|delete|patch) (['"])([^'"]+)\2/

def classify_path(path)
  p = path.to_s
  return :posts if p.start_with?('/posts')
  return :login if %w[/login /logout /chat].include?(p)
  return :api if p.start_with?('/api')
  return :test if p.start_with?('/test')
  :demo
end

def structural_stop?(line)
  return false unless line
  return true if line =~ /^  (JWT_ACCESS_TTL|JWT_REFRESH_TTL)\s/
  return true if line =~ /^  helpers do\n$/
  return true if line =~ /^  schedule /
  return true if line =~ /^  consume_queue /
  return true if line =~ /^  Cloudflare::DurableObject/
  return true if line =~ /^  CHAT_MODELS\s/
  return true if line =~ /^  CHAT_HISTORY_LIMIT\s/
  return true if line =~ /^  CHAT_HISTORY_TTL\s/
  return true if line =~ /^  CHAT_SYSTEM_PROMPT\s/
  return true if line =~ /^  def self\.extract_ai_text/
  return true if line =~ /^  SESSION_COOKIE_TTL\s/
  return true if line =~ /^  SESSION_COOKIE_NAME\s/
  return true if line =~ /^  def verify_session_cookie/
  return true if line =~ /^  def mint_session_cookie/
  return true if line =~ /^  def current_session_user/
  false
end

def trim_route_chunk(chunk)
  return chunk if chunk.nil? || chunk.empty?
  last_i = chunk.rindex { |l| l =~ /^  end\n$/ }
  return chunk unless last_i
  chunk[0..last_i]
end

# `canonical_all.rb` lines are indented with 2 spaces (as if inside `class App`). Fragment
# files are read alone, so strip that common leading 2 spaces for a top-level look.
def dedent_route_chunk_lines(chunk)
  chunk.map { |line| line.sub(/\A  /, '') }
end

def route_starts?(line)
  line =~ ROUTE_HEAD
end

lines = File.readlines(ALL)
hdr = []
i = 0
while i < lines.size && !route_starts?(lines[i])
  hdr << lines[i]
  i += 1
end
inner = lines[i..]

route_chunks = []
j = 0
while j < inner.size
  line = inner[j]
  unless route_starts?(line)
    j += 1
    next
  end
  start = j
  j += 1
  while j < inner.size
    break if route_starts?(inner[j])
    break if structural_stop?(inner[j])
    j += 1
  end
  route_chunks << trim_route_chunk(inner[start...j])
end

FileUtils.mkdir_p(FRAG)

meta = [] # [{ idx:, cat:, path: }]

route_chunks.each_with_index do |chunk, idx|
  first = chunk.find { |l| l =~ ROUTE_HEAD }
  path = first && (first =~ ROUTE_HEAD && Regexp.last_match(3))
  cat = classify_path(path)
  meta << { idx: idx + 1, cat: cat, path: path }
  fname = format('route_%03d.rb', idx + 1)
  body = +"# frozen_string_literal: true\n"
  body << "# Route fragment #{idx + 1} — #{cat} #{path}\n"
  body << dedent_route_chunk_lines(chunk).join
  File.write(File.join(FRAG, fname), body)
end

bootstrap = +"# frozen_string_literal: true\n"
bootstrap << "# Auto-generated by tools/split_routes_to_fragments.rb — registration order for `App`.\n"
bootstrap << "# Route bodies use Sinatra DSL; they are NOT `require`d — see `instance_eval` loop in app/app.rb.\n"
(1..meta.size).each do |n|
  bootstrap << "# fragments/route_#{format('%03d', n)}\n"
end
File.write(File.join(ROOT, 'app/routes/bootstrap.rb'), bootstrap)

%i[demo posts login api test].each do |sym|
  ids = meta.select { |m| m[:cat] == sym }.map { |m| m[:idx] }.sort
  next if ids.empty?

  buf = +"# frozen_string_literal: true\n"
  buf << "# Domain: #{sym} — fragment indices #{ids.join(', ')} (documentation only; routes load via app/app.rb).\n"
  ids.each do |id|
    buf << "# fragments/route_#{format('%03d', id)}\n"
  end
  File.write(File.join(ROOT, 'app/routes', "#{sym}.rb"), buf)
end

puts "Wrote #{meta.size} fragments + bootstrap + domain loaders"
