# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.4.0'

gem 'rake'
gem 'opal-homura',    '= 1.8.3.rc1.5', require: 'opal'
gem 'homura-runtime', '= 0.3.5'
gem 'sinatra-homura', '= 0.3.2'
